aws.region=ap-south-1
cart.table-name=cart_details
cart.create-table-on-startup=false

# Uncomment for local DynamoDB, for example when using dynamodb/docker-compose.yml.
 aws.dynamodb.endpoint-override=http://localhost:8000
